#!/usr/bin/env python3
"""Generate the King County city × permit-type coverage scorecard.

Single source of truth: routing_data.json. Emits the markdown block that lives
in README.md between the SCORECARD markers. Re-run after any routing change:

    python3 scripts/gen_scorecard.py --check   # fail if README is stale
    python3 scripts/gen_scorecard.py --write    # rewrite the README block
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "routing_data.json")
README = os.path.join(ROOT, "README.md")

BEGIN = "<!-- BEGIN SCORECARD (generated by scripts/gen_scorecard.py) -->"
END = "<!-- END SCORECARD -->"
BEGIN_SUM = "<!-- BEGIN COVERAGE (generated by scripts/gen_scorecard.py) -->"
END_SUM = "<!-- END COVERAGE -->"

# Cities with a dedicated live integration (not MyBuildingPermit).
DEDICATED = {"renton": "Renton (EnerGov)",
             "seattle": "Seattle (SDCI Open Data)",
             "bellevue": "Bellevue (Open Data)",
             "shoreline": "Shoreline (eTRAKiT)"}

# Display names where title-casing the routing_data key is wrong.
NAME_OVERRIDES = {"seatac": "SeaTac"}


def display_name(city):
    key = city.lower()
    if key in NAME_OVERRIDES:
        return NAME_OVERRIDES[key]
    return " ".join(w.capitalize() for w in city.split())

CELL = {
    "yes": "✅",
    "lni": "➖ L&I",
    "gap": "⚠️ gap",
    "no": "🔴",
}


def load():
    d = json.load(open(DATA))
    kc = sorted(d["king_county_cities"], key=str.lower)
    mbp = {c.lower() for c in d["cities_on_mbp"]}
    own_elec = {c.lower() for c in d["cities_own_electrical"]}
    return d, kc, mbp, own_elec


def classify(city, mbp, own_elec):
    key = city.lower()
    on_mbp = key in mbp
    dedicated = key in DEDICATED
    owns_elec = key in own_elec
    live_building = on_mbp or dedicated

    # source label
    if dedicated:
        source = DEDICATED[key]
    elif on_mbp:
        source = "MyBuildingPermit"
    else:
        source = "—"

    # electrical — verified against MBP feeds 2026-07-15 (see B7 in the epic):
    #   A city's own electrical permits live in its feed (MBP or a dedicated
    #   integration) only when the city self-runs electrical. Cities that don't
    #   self-run it have their electrical issued by WA L&I, so it comes from the
    #   L&I layer regardless of building coverage (e.g. Shoreline: building via
    #   eTRAKiT, electrical via L&I). A city that self-runs electrical but has no
    #   feed we search is a genuine gap.
    if not owns_elec:
        electrical = "lni"          # state (L&I) issues this city's electrical, 2020+
    elif dedicated or on_mbp:
        electrical = "yes"          # city runs electrical and we have its feed
    else:
        electrical = "gap"          # self-run electrical, no feed we search

    building = "yes" if live_building else "no"
    trade = "yes" if live_building else "no"       # mechanical / plumbing
    landuse = "yes" if live_building else "no"

    # status
    if live_building:
        status = "🟢 Live"
    elif electrical == "lni":
        status = "🟡 Partial"       # only L&I electrical retrievable; rest is a portal link
    else:
        status = "🔴 Fallback"      # link only

    return {
        "city": display_name(city), "status": status, "source": source,
        "building": building, "electrical": electrical,
        "trade": trade, "landuse": landuse,
    }


def render(rows):
    gap_cities = [r["city"] for r in rows if r["electrical"] == "gap"]
    out = [BEGIN, "", "### Coverage scorecard", "",
           "Auto-generated from `routing_data.json` "
           "(`python3 scripts/gen_scorecard.py --write`). "
           "One row per King County city.", "",
           "**Legend** — ✅ retrievable · ➖ L&I electrical only (2020+) · "
           "⚠️ gap (city self-runs electrical, not yet integrated) · 🔴 portal link only",
           "",
           "| City | Status | Source | Building | Electrical | Mech/Plumb | Land Use |",
           "|---|---|---|---|---|---|---|"]
    tally = {"🟢 Live": 0, "🟡 Partial": 0, "🔴 Fallback": 0}
    for r in rows:
        tally[r["status"]] += 1
        out.append("| {city} | {status} | {source} | {b} | {e} | {t} | {l} |".format(
            city=r["city"], status=r["status"], source=r["source"],
            b=CELL[r["building"]], e=CELL[r["electrical"]],
            t=CELL[r["trade"]], l=CELL[r["landuse"]]))
    # County-level row (unincorporated King County): building/septic/critical-areas
    # via the MyBuildingPermit "King County" jurisdiction; electrical via L&I.
    out.append("| _King County (unincorp.)_ | 🟢 Live | MyBuildingPermit (King County) "
               "| ✅ | ➖ L&I | ✅ | ✅ |")
    total = len(rows)
    out += ["",
            f"**Coverage:** {tally['🟢 Live']}/{total} live · "
            f"{tally['🟡 Partial']}/{total} partial (L&I electrical only) · "
            f"{tally['🔴 Fallback']}/{total} fallback. "
            "Plus **King County (unincorporated)** for county-level permits "
            "(septic, critical areas, grading).",
            "",
            "> ⚠️ **Electrical gaps:** " + (
                ", ".join(gap_cities) if gap_cities else "none"
            ) + ". These cities self-run their electrical program (so L&I is skipped) "
            "and are not on MyBuildingPermit, leaving their electrical permits in no "
            "feed we search. MBP cities that self-run electrical (Burien, Federal Way, "
            "Kirkland, Mercer Island, Sammamish) are **not** gaps — verified 2026-07-15 "
            "that MBP carries their electrical history. Closing the remaining gaps is "
            "tracked in the coverage epic.",
            "", END]
    return "\n".join(out)


def render_summary(rows):
    """One-line coverage badge for the top of the README (kept in sync here)."""
    tally = {"🟢 Live": 0, "🟡 Partial": 0, "🔴 Fallback": 0}
    for r in rows:
        tally[r["status"]] += 1
    total = len(rows)
    return "\n".join([
        BEGIN_SUM, "",
        f"**Coverage today:** 🟢 **{tally['🟢 Live']}/{total}** cities fully live · "
        f"🟡 **{tally['🟡 Partial']}/{total}** electrical-only (via L&I) · "
        f"🔴 **{tally['🔴 Fallback']}/{total}** portal-link fallback · plus "
        "unincorporated King County. See the coverage scorecard below for the "
        "per-city breakdown.", "",
        END_SUM,
    ])


def replace_region(text, begin, end, block):
    if begin not in text or end not in text:
        raise SystemExit(f"markers {begin!r}/{end!r} not found in README.md")
    return text[:text.index(begin)] + block + text[text.index(end) + len(end):]


def main():
    d, kc, mbp, own_elec = load()
    rows = [classify(c, mbp, own_elec) for c in kc]
    block = render(rows)
    summary = render_summary(rows)

    mode = sys.argv[1] if len(sys.argv) > 1 else "--print"
    if mode == "--print":
        print(summary)
        print()
        print(block)
        return
    readme = open(README).read()
    new = replace_region(readme, BEGIN, END, block)
    new = replace_region(new, BEGIN_SUM, END_SUM, summary)
    if mode == "--check":
        sys.exit(0 if readme == new else
                 "README coverage/scorecard is stale — run --write")
    if mode == "--write":
        open(README, "w").write(new)
        print("README coverage + scorecard updated.")


if __name__ == "__main__":
    main()
